<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="erp42_model" params="">

        <!-- ======================================== Variables ======================================== -->

        <!-- Arguments -->
        <xacro:arg name="robot_namespace" default="/" />
        <xacro:include filename="$(find erp42_description)/urdf/erp42_wheel.xacro" />

        <!-- Constants -->
        <xacro:property name="PI" value="3.14159"/>

        <!-- Wheel geometry (from 175/60R13) -->
        <xacro:property name="wheel_length" value="0.175" />
        <xacro:property name="wheel_radius" value="0.270" />

        <!-- Kinematics -->
        <xacro:property name="wheelbase" value="1.040" />
        <xacro:property name="track"     value="0.985" />

        <!-- Bumper dimensions -->
        <xacro:property name="bumper_x_size" value="0.220" />
        <xacro:property name="bumper_y_size" value="1.000" />
        <xacro:property name="bumper_z_size" value="0.150" />

        <!-- ======================================== Links ======================================== -->

        <!-- Base Footprint -->
        <link name="base_footprint"/>

        <!-- Base link -->
        <link name="base_link"/>

        <!-- Chassis -->
        <link name="chassis">

            <!-- Inertia -->
            <inertial>
                <mass value="160"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="20.43" ixy="0.584" ixz="-0.191" iyy="54.197" iyz="-0.2449" izz="72.2588"/>
            </inertial>

            <!-- Chassis -->
            <collision>
                <origin xyz="0.02 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="1.580 0.950 0.316"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="file://$(find erp42_description)/meshes/erp42_chassis.dae"  scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>

            <!-- Front bumper -->
            <collision>
                <origin xyz="${wheelbase/2 + bumper_x_size/2 + 0.290} 0 ${-bumper_z_size/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${bumper_x_size} ${bumper_y_size} ${bumper_z_size}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="${wheelbase/2 + bumper_x_size/2 + 0.290} 0 ${-bumper_z_size/2}" rpy="0 0 0" />
                <geometry>
                    <mesh filename="file://$(find erp42_description)/meshes/erp42_bumper.dae"  scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>

            <!-- Rear bumper -->
            <collision>
                <origin xyz="${-wheelbase/2 - bumper_x_size/2 - 0.250} 0 ${-bumper_z_size/2}" rpy="0 0 ${PI}" />
                <geometry>
                    <box size="${bumper_x_size} ${bumper_y_size} ${bumper_z_size}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="${-wheelbase/2 - bumper_x_size/2 - 0.250} 0 ${-bumper_z_size/2}" rpy="0 0 ${PI}" />
                <geometry>
                    <mesh filename="file://$(find erp42_description)/meshes/erp42_bumper.dae"  scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>

        </link>

        <!-- Steering assemblies -->
        <link name="front_left_steering_hub">

            <!-- Inertia -->
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
            </inertial>

        </link>

        <link name="front_right_steering_hub">

            <!-- Inertia -->
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
            </inertial>

        </link>

        <!-- Wheels -->
        <xacro:erp42_wheel link_name="front_left_wheel" />
        <xacro:erp42_wheel link_name="front_right_wheel"/>
        <xacro:erp42_wheel link_name="rear_left_wheel"  />
        <xacro:erp42_wheel link_name="rear_right_wheel" />

        <!-- ======================================== Joints ======================================== -->

        <!-- base_footprint to base_link -->
        <joint name="base_link_joint" type="fixed">
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
            <parent link="base_footprint" />
            <child link="base_link" />
        </joint>

        <!-- base_link to chassis -->
        <joint name="chassis_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <parent link="base_link" />
            <child link="chassis" />
        </joint>

        <!-- base_link to front_left_steering_hub -->
        <joint name="front_left_steering_hub_joint" type="revolute">
            <origin xyz="${wheelbase/2} ${track/2} 0" rpy="0 0 0" />
            <parent link="base_link"/>
            <child link="front_left_steering_hub"/>
            <axis xyz="0 0 1"/>
            <limit lower="-0.698132" upper="0.698132" effort="100" velocity="100"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>

        <!-- base_link to front_right_steering_hub -->
        <joint name="front_right_steering_hub_joint" type="revolute">
            <origin xyz="${wheelbase/2} ${-track/2} 0" rpy="0 0 0" />
            <parent link="base_link"/>
            <child link="front_right_steering_hub"/>
            <axis xyz="0 0 1"/>
            <limit lower="-0.698132" upper="0.698132" effort="100" velocity="100"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>

        <!-- front_left_steering_hub to front_right_wheel  -->
        <joint name="front_left_wheel_joint" type="continuous">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <parent link="front_left_steering_hub"/>
            <child link="front_left_wheel"/>
            <axis xyz="0 1 0"/>
        </joint>

        <!-- front_right_steering_hub to front_right_wheel  -->
        <joint name="front_right_wheel_joint" type="continuous">
            <origin xyz="0 0 0" rpy="${PI} 0 0" />
            <parent link="front_right_steering_hub"/>
            <child link="front_right_wheel"/>
            <axis xyz="0 -1 0"/>
        </joint>

        
        <joint name="rear_left_wheel_joint" type="continuous">
            <origin xyz="${-wheelbase/2} ${track/2} 0" rpy="0 0 0" />
            <parent link="base_link"/>
            <child link="rear_left_wheel"/>
            <axis xyz="0 1 0"/>
        </joint>

        <!-- base_link to rear_right_wheel -->
        <joint name="rear_right_wheel_joint" type="continuous">
            <origin xyz="${-wheelbase/2} ${-track/2} 0" rpy="${PI} 0 0" />
            <parent link="base_link"/>
            <child link="rear_right_wheel"/>
            <axis xyz="0 -1 0"/>
        </joint>

    </xacro:macro>
</robot>